### ISSUE TITLE
HTML formatting

### ISSUE THREAD

**Issue by mhbeals** [russlescai/atom-xsltransform#5]
XSL transform always prefaces with HTML header.  Can this be removed?  I transform into Markdown files, not HTML. (Thanks)

**Comment by russlescai** [comment]
Good idea @mhbeals.

I assumed the XSL would be transforming xml documents, however that doesn't have to be the case! 

I plan to add a feature to transform to any document type.

**Comment by mhbeals** [comment]
The file still transforms into 'text', it is just the unnecessary addition of the pre, head and body HTML elements that is noticable. Thanks!

**Comment by nicolaiax** [comment]
Yeah I was just gonna write that too. Thanks @russlescai for adding to the readme section. I now got it all to work but in my company we use xslt and transformations to create other xml files or text files so the html addition messes it up and we cannot use it. Another note is that your sample xml didn't have the xml declaration tag.

I've attached some screenshots of my test xml file, xslt and the finished output when running it in Oxygen XML Developer.

![screen shot 2015-07-23 at 11 14 10 am](https://cloud.githubusercontent.com/assets/13438891/8855689/2700b656-312c-11e5-817b-cc44288c3f12.png)
![screen shot 2015-07-23 at 11 14 26 am](https://cloud.githubusercontent.com/assets/13438891/8855688/270036b8-312c-11e5-952f-3bf6654c05e9.png)
![screen shot 2015-07-23 at 11 14 36 am](https://cloud.githubusercontent.com/assets/13438891/8855687/26fe2742-312c-11e5-9078-86d69a819789.png)

**Comment by russlescai** [comment]
With the latest version, you can specify the XSLT tool to use (which supports xslt v2) instead of using the native.

I have updated the README with some examples, let me know if you have any issues! :)

**Comment by mhbeals** [comment]
Could you please give a bit more detail.  I am not sure where to input the relevant external reference or how to format it.  I have saxon.jar (as part of my Oxygen directory).

**Comment by nicolaiax** [comment]
Thanks for the update @russlescai, I truly appreciate the effort. 

Here's the link to the saxon XSLT and XQuery processor (open-source) from http://sourceforge.net/projects/saxon/?source=typ_redirect. I then extracted the zip file once downloaded and added it to my Java Library Extensions folder (OSX = open your HD -> Library -> Java -> Extensions, added saxon9he.jar & saxon9-xqj.jar).  

I opened the xmltransform package settings in Atom (open config folder -> packages -> atom-xmltransform -> lib -> atom-xmltransform.coffee), this is the config part of the file where I changed the default "path":
  config:
    externalXslToolPath:
      type: 'string'
      default: 'java net.sf.saxon.Transform -s:%XML -xsl:%XSL'
      description: 'The path to an external Xsl tool. Use %XSL and %XML for file parameters'

Hope this helps anyone who wants to change the xslt processor. It worked for my example above.

**Comment by nicolaiax** [comment]
M. H. Beals: I updated one ticket with how to add saxon. I'm using Mac
(OSX) but it should be similar on windows as it's using java.

Here's what I wrote:

Here's the link to the saxon XSLT and XQuery processor (open-source) from
http://sourceforge.net/projects/saxon/?source=typ_redirect. I then
extracted the zip file once downloaded and added it to my Java Library
Extensions folder (OSX = open your HD -> Library -> Java -> Extensions,
added saxon9he.jar & saxon9-xqj.jar).

I opened the xmltransform package settings in Atom (open config folder ->
packages -> atom-xmltransform -> lib -> atom-xmltransform.coffee), this is
the config part of the file where I changed the default "path":
config:
externalXslToolPath:
type: 'string'
default: _'java net.sf.saxon.Transform -s:%XML -xsl:%XSL'_
description: 'The path to an external Xsl tool. Use %XSL and %XML for file
parameters'

Hope this helps anyone who wants to change the xslt processor. It worked
for my example above.

**Comment by mhbeals** [comment]
Sadly, I am still getting the same error: 

Unrecognized option: the 

Whether I use the sourceforge saxon or my EE version.

**Comment by nicolaiax** [comment]
M.H.Beals, if you want to send me your xslt and xml then I can try to run
it in Atom on my end. If you have any sensitive data please scramble the
xml before sending.

Questions:
1. Does it work in Oxygen when you run it there?
2. Did you check the config section and change the atom-xmltransform config
file (installed in the atom packaged folder)?
3. How many lines does you file have? there's a limitation to how many
lines saxon can handle (file size limit)
4. Did you add the saxon jars to your Java library (classpath in windows,
or added to the library folder for the runtime)?

My personal email address is nicolai.axelsen@gmail.com if you want to send
me some files and i can do a quick test for you to confirm that it will
work if you have it installed correctly.

rgds,

Nico

**Comment by mhbeals** [comment]
Issue has been resolved.  Do not use spaces in the xml file name.

**Comment by russlescai** [comment]
glad you got it working, @mhbeals . You can have spaces in the xml filename by using quotes around the parameters. e.g.:

```
saxon -s:"%XML" -xsl:"%XSL"
```
